### ISSUE TITLE
Performance Benchmarking

### ISSUE THREAD

**Issue by ronak2121** [enisz/node-date-parser#1]
Hi,

I was wondering if you've done any performance benchmarking of your parse operations against https://www.npmjs.com/package/date-and-time? Looking at your code; it looks a lot simpler (no regex for example); so I'd imagine it would be a lot faster.

I'm thinking of switching to using your functions if they are faster...

Thanks,

Ronak

**Comment by enisz** [comment]
Hi @ronak2121,

Sorry for the late response. No, I haven't done any performance benchmarking of this code. I only needed a small library for my pervious project where the performance wasn't a requirement (small, home project).

Maybe I'll do one, just out of curiosity when I have some free time.

**Comment by enisz** [comment]
Hi @ronak2121 ,

I just had some free time to do this benchmark. After cloning the date-and-time module's repository I started the benchmark on my pc to have a reference. Here are the results:

```
c:\wamp64\www\date-and-time\benchmark>node bench.js
Creating a list of random date string...
Starting the benchmark.

format(): 9283ms
format() with compile(): 5855ms (63%)
parse(): 9708ms
parse() with compile(): 5855ms (57%)
```

After this I wrote a similar benchmar script to my module which is using the exact same pattern:

```javascript
// Date parser module
const dateParser = require("../src/node-date-parser");
// Random number generator function
function rand(min, max) { return Math.floor(Math.random() * (max - min + 1) + min); }
// An array of generated dates
let dates = [];
// Number of dates to generate
let elements = 3000000;
// Helper variable to calculate durations
let start;

console.log(`Generating random dates between ${new Date(0)} and ${new Date(Date.now())}...`);

start = Date.now();
for(let i=0; i<elements; i++) {
    dates.push(new Date(rand(0, Date.now())));
}

console.log(`${elements} dates are generated in ${(Date.now() - start) / 1000} seconds.`);

console.log(`Parsing dates with the DateParser module...`);
start = Date.now();
for(let i=0; i<dates.length; i++) {
    dateParser.parse("E. j Y G:I:S A", dates[i]);
}

console.log(`${elements} dates parsed with the module in ${(Date.now() - start) / 1000} seconds.`)
```

After running this script I got these results:
```
C:\wamp64\www\node-date-parser>node benchmark/benchmark.js
Generating random dates between Thu Jan 01 1970 01:00:00 GMT+0100 (GMT+01:00) and Fri Aug 14 2020 22:21:32 GMT+0200 (GMT+02:00)...
3000000 dates are generated in 1.312 seconds.
Parsing dates with the DateParser module...
3000000 dates parsed with the module in 13.493 seconds.
```

It seems my module's performance is poorer a bit.

I will push this benchmark file to the repository shortly with some fixes in the package. If this is the benchmark you were looking for feel free to close th issue. If you have something else in your mind, let me know!
